### ISSUE TITLE
Problems creating instances of VolumePopulator CR

### ISSUE THREAD

**Issue by bswartz** [kubernetes-csi/volume-data-source-validator#30]
When I try this example:
```
kubectl apply -f - <<EOF
kind: VolumePopulator
apiVersion: populator.storage.k8s.io/v1beta1
metadata:
  name: hello-populator
sourceKind:
  group: hello.example.com
  kind: Hello
EOF
```

I get this error:
`Error from server (BadRequest): error when creating "STDIN": VolumePopulator in version "v1beta1" cannot be handled as a VolumePopulator: strict decoding error: unknown field "metadata.name"`

I only observe this with K8s 1.24.x and not 1.23.x, but I suspect it's due to a bad CRD.
